// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpOEq83wRB02oKsP8MQUwHHQO_4JebWzE',
    appId: '1:97806127182:web:c159ea873a69e29bb0f31f',
    messagingSenderId: '97806127182',
    projectId: 'authtutorial-e501e',
    authDomain: 'authtutorial-e501e.firebaseapp.com',
    storageBucket: 'authtutorial-e501e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3VIR-M0lhj3Bm_NfECSBYRuQ8TTAmVXc',
    appId: '1:97806127182:android:97eafee5ce881db0b0f31f',
    messagingSenderId: '97806127182',
    projectId: 'authtutorial-e501e',
    storageBucket: 'authtutorial-e501e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKVKYwRCeBYllshKa2X3CGxJP8pMw8Wbw',
    appId: '1:97806127182:ios:740af6032bbe1f57b0f31f',
    messagingSenderId: '97806127182',
    projectId: 'authtutorial-e501e',
    storageBucket: 'authtutorial-e501e.appspot.com',
    iosBundleId: 'com.example.boleiaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKVKYwRCeBYllshKa2X3CGxJP8pMw8Wbw',
    appId: '1:97806127182:ios:d999950076fc8934b0f31f',
    messagingSenderId: '97806127182',
    projectId: 'authtutorial-e501e',
    storageBucket: 'authtutorial-e501e.appspot.com',
    iosBundleId: 'com.example.boleiaApp.RunnerTests',
  );
}
